services:
  sistema_financeiro:
    build:
      context: ./docker/postgres
    container_name: sistema_financeiro
    environment:
      POSTGRES_USER: ${PG_SUPERUSER}
      POSTGRES_PASSWORD: ${PG_SUPERPASS}
      POSTGRES_DB: financeiro
    ports:
      - "15432:5432"
    volumes:
      - pg_finance_data:/var/lib/postgresql/data
    networks:
      - net_sistema_financeiro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${PG_SUPERUSER} -d postgres"]
      interval: 5s
      timeout: 3s
      retries: 20

  sistema_vendas:
    build:
      context: ./docker/mysql
    container_name: sistema_vendas
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: vendas
      MYSQL_USER: ${MYSQL_APP_USER}
      MYSQL_PASSWORD: ${MYSQL_APP_PASS}
    ports:
      - "13306:3306"
    volumes:
      - mysql_sales_data:/var/lib/mysql
    networks:
      - net_sistema_vendas
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -uroot -p$${MYSQL_ROOT_PASSWORD} --silent"]
      interval: 5s
      timeout: 5s
      retries: 30

  sistema_suporte:
    build:
      context: ./docker/mongo
    container_name: sistema_suporte
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASS}
      MONGO_INITDB_DATABASE: suporte
    ports:
      - "27017:27017"
    volumes:
      - mongo_support_data:/data/db
    networks:
      - net_sistema_suporte
    healthcheck:
      test: ["CMD-SHELL", "mongosh --quiet --username ${MONGO_ROOT_USER} --password ${MONGO_ROOT_PASS} --eval 'db.adminCommand({ ping: 1 })' admin || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 30

  ingestor:
    build:
      context: ./ingestor
    container_name: ingestor
    volumes:
      - ${HOME}/.aws:/root/.aws:ro
    environment:
      AWS_REGION: ${AWS_REGION}
      AWS_DEFAULT_REGION: ${AWS_DEFAULT_REGION}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      S3_BUCKET: ${S3_BUCKET}
      # Postgres (financeiro)
      PG_HOST: sistema_financeiro
      PG_PORT: "5432"
      PG_DB: financeiro
      PG_USER: ${PG_SUPERUSER}
      PG_PASS: ${PG_SUPERPASS}

      # MySQL (vendas)
      MYSQL_HOST: sistema_vendas
      MYSQL_PORT: "3306"
      MYSQL_DB: vendas
      MYSQL_USER: ${MYSQL_APP_USER}
      MYSQL_PASS: ${MYSQL_APP_PASS}

      # Mongo (suporte)
      MONGO_HOST: sistema_suporte
      MONGO_PORT: "27017"
      MONGO_DB: suporte
      MONGO_USER: ${MONGO_ROOT_USER}
      MONGO_PASS: ${MONGO_ROOT_PASS}

    depends_on:
      sistema_financeiro:
        condition: service_healthy
      sistema_vendas:
        condition: service_healthy
      sistema_suporte:
        condition: service_healthy
    networks:
      - net_sistema_financeiro
      - net_sistema_vendas
      - net_sistema_suporte
 
  terraform:
    build:
      context: ./iac
      dockerfile: Dockerfile
    container_name: terraform
    working_dir: /iac
    entrypoint: ["sleep"]
    command: ["infinity"]

    #volumes:
     # - ./iac_state:/state

    environment:
      AWS_REGION: ${AWS_REGION}
      AWS_DEFAULT_REGION: ${AWS_DEFAULT_REGION}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
     # TF_DATA_DIR: /state/.terraform
     # TF_CLI_ARGS_plan: "-state=/state/terraform.tfstate"
     # TF_CLI_ARGS_apply: "-state=/state/terraform.tfstate"
 

volumes:
  pg_finance_data:
  mysql_sales_data:
  mongo_support_data:

networks:
  net_sistema_financeiro:
    driver: bridge
  net_sistema_vendas:
    driver: bridge
  net_sistema_suporte:
    driver: bridge
